apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp-argo-application
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/BrianKim913/weekly4_config.git
      targetRevision: HEAD
      path: backend
    - repoURL: https://github.com/BrianKim913/weekly4_config.git
      targetRevision: HEAD
      path: frontends
  destination:
    server: https://kubernetes.default.svc
    namespace: backend

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true